import Head from "next/head";
import styles from "../styles/Home.module.css";

import about from "../components/home/about";
import { useState } from "react";

const Home = () => {
  const [file, setFile] = useState();
  const [filename, setFileName] = useState("Choose File");
  const [prediction, setPrediction] = useState(null);

  const onChange = (e) => {
    setFile(e.target.files[0]);
    setFileName(e.target.files[0].name);
  };

  const onSubmit = async (e) => {
    e.preventDefault();
    const formData = new FormData();
    formData.append("file", file);
    console.log(file);

    fetch("http://localhost:5000/upload", {
      method: "POST",
      body: formData,
    })
      .then((res) => res.json())
      .then((data) => {
        console.log(data);
        setPrediction(data);
      });
  };

  return (
    <div>
      <Head>
        <title>Public anomaly detection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <nav className="flex items-center justify-between flex-wrap bg-teal-500 p-6">
          <div className="flex items-center flex-shrink-0 text-white mr-6">
            <span className="font-semibold text-xl tracking-tight">
              Public anomaly detection
            </span>
          </div>
          <div className="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
            <div className="text-sm lg:flex-grow">
              <a
                href="#about"
                className="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4"
              >
                About
              </a>
              <a
                href="#working"
                className="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4"
              >
                Working
              </a>
              <a
                href="#team"
                className="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4"
              >
                Team
              </a>
              <a
                href="#ideas"
                className="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white"
              >
                Future Ideas
              </a>
            </div>
          </div>
        </nav>

        <section id="about">
          <div className="p-10 text-2xl font-semibold text-teal-200">
            About the Project
          </div>
          <div className="px-10 text-xl">
            Our model checks the surveillance footages and uses a model which is
            made using LSTM Convolutional Autoencoder. It will alert the
            security guard about any event which can be considered as an
            anomaly.
          </div>
        </section>

        <section id="working">
          <div className="p-10 text-2xl text-teal-200">Working</div>
          <div className="px-10">
            <form onSubmit={onSubmit}>
              <div className="custom-file">
                <input
                  type="file"
                  className="custom-file-input"
                  id="customFile"
                  onChange={onChange}
                />
                <label className="custom-file-label" htmlFor="customFile">
                  {filename}
                </label>
              </div>
              <input
                type="submit"
                value="Upload"
                className="btn btn-primary btm-block mt-4 bg-teal-200 text-black rounded-lg px-5 py-3"
              />
            </form>
            {prediction && <h1>{prediction.message}</h1>}
          </div>
        </section>

        <section id="ideas">
          <div className="p-10 text-2xl font-semibold text-teal-200">
            Future Ideas
          </div>
          <div className="px-14 text-xl">
            <li>Improve the accuracy of the model .</li>
            <li>
              Include action alerts for anomalies detected via sms or call to
              emergency services .
            </li>
          </div>
        </section>

        <section id="team">
          <div className="p-10 text-2xl text-teal-200 font-semibold">
            About the Team
          </div>
          <div className="flex justify-around flex-wrap">
            <div className="max-w-xs bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700 m-3">
              <a href="#">
                <img
                  className="rounded-t-lg"
                  src="https://shockwave24.s3.ap-south-1.amazonaws.com/karan.png"
                  alt="karan"
                />
              </a>
              <div className="p-5">
                <a href="#">
                  <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                    Karan Pargal
                  </h5>
                </a>
                <p className="mb-3 font-normal text-gray-700 dark:text-gray-400">
                  CSe student at SRM University || ML Enthusiast || Member @
                  Next Tech Lab || Technical Lead @GitHub Community SRM
                </p>
              </div>
            </div>
            <div className="max-w-xs bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700 m-3">
              <a href="#">
                <img
                  className="rounded-t-lg"
                  src="https://shockwave24.s3.ap-south-1.amazonaws.com/utkarsh.png"
                  alt=""
                />
              </a>
              <div className="p-5">
                <a href="#">
                  <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                    Utkarsh Rastogi
                  </h5>
                </a>
                <p className="mb-3 font-normal text-gray-700 dark:text-gray-400">
                  CGI & VFX artist | Editorial Lead at SRMKZILLA | Associate at
                  Next Tech Lab
                </p>
              </div>
            </div>
            <div className="max-w-xs bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700 m-3">
              <a href="#">
                <img
                  className="rounded-t-lg"
                  src="https://shockwave24.s3.ap-south-1.amazonaws.com/pranav.png"
                  alt=""
                />
              </a>
              <div className="p-5">
                <a href="#">
                  <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                    Pranav Gupta
                  </h5>
                </a>
                <p className="mb-3 font-normal text-gray-700 dark:text-gray-400">
                  Syndicate at Next Tech Lab, AI/ML Researcher and Engineer,
                  Computer Vision Enthusiast
                </p>
              </div>
            </div>
            <div className="max-w-xs bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700 m-3">
              <a href="#">
                <img
                  className="rounded-t-lg"
                  src="https://shockwave24.s3.ap-south-1.amazonaws.com/sarthak.png"
                  alt=""
                />
              </a>
              <div className="p-5">
                <a href="#">
                  <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                    Sarthak Sachdeva
                  </h5>
                </a>
                <p className="mb-3 font-normal text-gray-700 dark:text-gray-400">
                  backend developer Intern at CGS || Member @Alexa developers
                  SRM || Technical Lead @GitHub Community SRM || Member @MLSA
                  SRM
                </p>
              </div>
            </div>
          </div>
        </section>
      </section>
    </div>
  );
};

export default Home;
